image: alpine

before_script:
- apk update
- apk add doxygen


test:
  script:
  - doxygen doxygen/Doxyfile
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  tags: 
    - debian
  
  
pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags: 
    - debian  
