name: Generate Doxygen Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate:
    name: Generate and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate
      uses: mattnotmitt/doxygen-action@v1.9.8
      with:
        working-directory: '.'
        doxyfile-path: './doxygen/Doxyfile'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      # If you're changing the branch from main,
      # also change the `main` in `refs/heads/main`
      # below accordingly.
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doxygen/documentation/html
